apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: grafana
  labels:
    cloud.googleapis.com/location: us-central1
spec:
  template:
    spec:
      serviceAccountName: grafana-run@opentelemetry-nrb.iam.gserviceaccount.com
      containers:
        - name: grafana
          image: us-central1-docker.pkg.dev/opentelemetry-nrb/cloud-run-source-deploy/grafana-cloud@sha256:89b213fd6960a410f6071ca1de740aa7c5db6eafef79d8a5f7ae0140a722b1ff
          ports:
            - containerPort: 8080
          env:
            - name: GF_SERVER_HTTP_PORT
              value: "8080"
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "true"
            - name: GF_AUTH_ANONYMOUS_ORG_ROLE
              value: "Admin"
            - name: GF_AUTH_DISABLE_LOGIN_FORM
              value: "true"
          resources:
            limits:
              memory: 512Mi
