apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: grafana
  labels:
    cloud.googleapis.com/location: us-central1
spec:
  template:
    spec:
      serviceAccountName: grafana-run@opentelemetry-nrb.iam.gserviceaccount.com
      containers:
        - name: grafana
          image: us-central1-docker.pkg.dev/opentelemetry-nrb/cloud-run-source-deploy/grafana-cloud:latest
          ports:
            - containerPort: 8080
          env:
            - name: GF_SERVER_HTTP_PORT
              value: "8080"
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "true"
            - name: GF_AUTH_ANONYMOUS_ORG_ROLE
              value: "Admin"
            - name: GF_AUTH_DISABLE_LOGIN_FORM
              value: "true"
          resources:
            limits:
              memory: 512Mi
